name: Bug report
description: Report a reproducible defect
labels: [bug]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Include expected behavior and actual behavior.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction steps
      description: Minimal steps to reproduce.
    validations:
      required: true
  - type: input
    attributes:
      label: Version
      placeholder: e.g. 1.0.0
    validations:
      required: true
