name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem to solve
      description: What limitation are you hitting?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: Describe the design/API you want.
    validations:
      required: true
